= Java 21

== What's new?

* Sequenced Collections
* Code snippets in Javadocs
* Generational ZGC
* Record Patterns
* Pattern matching for switch
* Virtual Threads
* Serialization?
* New methods: emoji

== Sequenced Collections

=== New Interface

[,java]
----
interface SequencedCollection<E> extends Collection<E> {
    SequencedCollection<E> reversed();

    // methods promoted from Deque
    void addFirst(E);
    void addLast(E);
    E getFirst();
    E getLast();
    E removeFirst();
    E removeLast();
}
----

* Implemented by collections like:
    ** `List`
    ** `Deque`
    ** `NavigableSet`
    ** `LinkedHashSet`

=== Reverse traversal

.Before
[,java]
----
for (int i = list.size() - 1; i >= 0; i--) {
    var item = list.get(i);
    // do something
}
----

.After
[,java]
----
for (var item : list.reversed()) {
    // do something
}

list.reversed().stream()
    .map(Object::toString)
    .toList();
----

=== Interview Question

Reverse a linked list

.Solution
[,java]
----
var list = new LinkedList<Integer>();
list.reverse();
----

=== First and Last

|===
| | Before | After

| Get last
| `list.get(list.size() - 1)`
| `list.getLast()`

| Remove last
| `list.remove(list.size() - 1)`
| `list.removeLast()`

| Add last
| `list.add(list.size() - 1)`
| `list.addLast()`
|===

`(get|add|remove)First()` works the same way

== Code Snippets in Javadocs

=== Code Snippets Today

[,java]
----
/**
 * Streams example
 *
 * <pre>{@code
 *     int sum = widgets.stream()
 *                      .filter(w -> w.getColor() == RED)
 *                      .mapToInt(w -> w.getWeight())
 *                      .sum();
 * }</pre>
*/
----

* `<pre>` is required to preserve whitespace
* `{@code}` properly displays characters like `@`, `<`, and `>` in the code example

=== Code Snippets with Java 21

[,java]
----
/**
 * Streams example
 *
 * {@snippet :
 *     int sum = widgets.stream()
 *                      .filter(w -> w.getColor() == RED)
 *                      .mapToInt(w -> w.getWeight())
 *                      .sum();
 * }
*/
----

=== External Snippets

[,java]
----
/**
 * Streams example
 *
 * {@snippet class="StreamExample"}
*/
----

=== Highlighting

[source,subs="verbatim,quotes"]
----
class HelloWorld {
    public static void main(String... args) {
        System.out.*println*("Hello World!");
    }
}
----

See https://openjdk.org/jeps/413[JEP 413: Code Snippets in Java Documentation]

== Generational Z Garbage Collector (ZGC)

=== Generational Hypothesis

* Most objects survive for a short period of time
* In other words, an object that was just created is more likely to die (and be collected) than an object that has been around for a while
* Garbage collectors like G1 take advantage of this by splitting the heap into a Young Generation and Old generation
* ZGC will now be doing the same, improving performance

=== Video

* slight increase in memory footprint and startup
* modest throughtput improvement (5 - 15%)
* Serialization is faster
* G1: region size can be increased to 512 (good for apps with large objects)
    ** single mark bitmap (1% improvement)
    ** concurrent refinement: improved throughput

== Record Patterns

[,java]
----
record Point(int x, int y) {}

static void printSum(Object obj) {
    if (obj instanceof Point p) {
        int x = p.x();
        int y = p.y();
        System.out.println(x+y);
    }
}
----

[,java]
----
static void printSum(Object obj) {
    if (obj instanceof Point(int x, int y)) {
        System.out.println(x+y);
    }
}
----

.Nested
[,java]
----
record Point(int x, int y) {}
enum Color { RED, GREEN, BLUE }
record ColoredPoint(Point p, Color c) {}
record Rectangle(ColoredPoint upperLeft, ColoredPoint lowerRight) {}
static void printUpperLeftColoredPoint(Rectangle r) {
    if (r instanceof Rectangle(ColoredPoint ul, ColoredPoint lr)) {
         System.out.println(ul.c());
    }
}

static void printColorOfUpperLeftPoint(Rectangle r) {
    if (r instanceof Rectangle(ColoredPoint(Point p, Color c),
                               ColoredPoint lr)) {
        System.out.println(c);
    }
}
----

Need to read more of the jep

== Virtual Threads

TODO: demo

== Conclusion

== Looking Ahead

* String Templates
* Structured Concurrency
* Foreign function and memory API
* Unnamed patterns and variables
* Unnamed classes and instance main methods
* Scoped values
* Vector API
