= Java 21

== What's new?

* Sequenced Collections
* Code snippets in Javadocs
* Generational ZGC
* Record Patterns
* Pattern matching for switch
* Virtual Threads
* Serialization?
* New methods: emoji

== Sequenced Collections

=== New Interface

[,java]
----
interface SequencedCollection<E> extends Collection<E> {
    SequencedCollection<E> reversed();

    // methods promoted from Deque
    void addFirst(E);
    void addLast(E);
    E getFirst();
    E getLast();
    E removeFirst();
    E removeLast();
}
----

* Implemented by collections like:
    ** `List`
    ** `Deque`
    ** `NavigableSet`
    ** `LinkedHashSet`

=== Reverse traversal

.Before
[,java]
----
for (int i = list.size() - 1; i >= 0; i--) {
    var item = list.get(i);
    // do something
}
----

.After
[,java]
----
for (var item : list.reversed()) {
    // do something
}

list.reversed().stream()
    .map(Object::toString)
    .toList();
----

=== Interview Question

Reverse a linked list

.Solution
[,java]
----
var list = new LinkedList<Integer>();
list.reverse();
----

=== First and Last

|===
| | Before | After

| Get last
| `list.get(list.size() - 1)`
| `list.getLast()`

| Remove last
| `list.remove(list.size() - 1)`
| `list.removeLast()`

| Add last
| `list.add(list.size() - 1)`
| `list.addLast()`
|===

`(get|add|remove)First()` works the same way

== Code Snippets in Javadocs

=== Code Snippets Today

[,java]
----
/**
 * Streams example
 *
 * <pre>{@code
 *     int sum = widgets.stream()
 *                      .filter(w -> w.getColor() == RED)
 *                      .mapToInt(w -> w.getWeight())
 *                      .sum();
 * }</pre>
*/
----

* `<pre>` is required to preserve whitespace
* `{@code}` properly displays characters like `@`, `<`, and `>` in the code example

=== Code Snippets with Java 21

[,java]
----
/**
 * Streams example
 *
 * {@snippet :
 *     int sum = widgets.stream()
 *                      .filter(w -> w.getColor() == RED)
 *                      .mapToInt(w -> w.getWeight())
 *                      .sum();
 * }
*/
----

=== External Snippets

[,java]
----
/**
 * Streams example
 *
 * {@snippet class="StreamExample"}
*/
----

=== Highlighting

[source,subs="verbatim,quotes"]
----
class HelloWorld {
    public static void main(String... args) {
        System.out.*println*("Hello World!");
    }
}
----

See https://openjdk.org/jeps/413[JEP 413: Code Snippets in Java Documentation]

== Virtual Threads

TODO: demo

== Conclusion

== Looking Ahead

* String Templates
* Structured Concurrency
* Foreign function and memory API
* Unnamed patterns and variables
* Unnamed classes and instance main methods
* Scoped values
* Vector API
