= Java 21

== Intro

- Going to talk about all of the new features that were added to java 21 after java 17
- Here are the topics we'll be discussing - note that I'm only discussing finalized features (nothing in preview)
- Trying to give you an overview of everything, so I'll be moving fast in some parts, but we will have time for questions at the end
- And if we don't have enough time for all questions, I can answer them later on slack

== Sequenced

- Let's start with sequence collections
- new interface in java that adds methods like addFirst/Last, removeFirst/Last, etc
- many collections have been retrofitted with this interface
- it's not a game changer, but it definitely does a better job at communicating intent - no more minus 1 indexing
- also has a reverse method that returns a view of the collection
- note that this is not a copy of the collections it's a view - so if you modify the original collection it will show up in the view
- Now I know we are never going to leave [place], but if theoretically you were interviewing again and they ask you to reverse a linked list... this is how you'd do it

== Code snippets

- We are all good developers here and document our code, so i know you will be excited for this one
- today... gotta do the pre and the code tags - I always have to lookup how to do it
- java now has a built in snippet tag
- intellij actually does basic autocompletion inside code snippets
- what I think is pretty powerful is external snippets they allow you to write examples in a normal java file with code completion
- if you set it up right, you can link to tests that actually compile
- there are actually a lot of other features like highlighting but I'm not going to cover them because they're not the most interesting thing to discuss and it's easy to look them up

== ZGC

- A little bit of background on GCs
- JDK has several GCs that have different trade-offs between throughput, latency, and overhead
- The default GC of the jdk is G1 which aims to have a good balance between latency and throughput
- the Z Garbage Collector, focuses on low latency
- sub ms pause times on TB size heaps
- ZGC already exists - you can already use it, but java 21 makes it generational
- I'm not going to go into how generational garbage collectors work
- But the idea is most objects die shortly after creation
- Think about creating a bunch of duration objects or optionals, these objects are usually not used outside of a function call
- collect more frequently

=== Netflix

- Using the right GC can have significant performance benefits
- I have just one example from a netflix blog post
- What was really interesting is the throughput of ZGC was actually very comparable to G1
- And that actually leads me to the most important point of GCs - you should just try different GCs for your app and profile them

== Record patterns

- where we get into more functional programming stuff
- this is a basic record pattern example
- you might be saying this doesn't look much better and I actually agree with you, this is a very simple example but we are going to build into something more powerful, just stick with me a bit longer
- contrived example

=== Nested

- also enabled nested record patterns

=== Declare what you want

- speaks for itself - much more concise and does a better job of communicating intent
- the compiler is essentially doing these checks for you behind the scenes

== Switch

- exhaustive: add or remove
- Method is taking in a generic type and then doing things based on the specific type
- nice side effect

== Virtual Threads

- demonstrate ~10k platform threads: show slowness
- demonstrate ~20k: show OOM
- switch to virtual threads
- do 1 Million threads
- virtual memory maps large virtual address space to a limited amount of physical RAM, virtual threads map to a small number of OS threads.
- Green threads share a single operating system thread through co-operative concurrency. The main benefit of coroutines and green threads is ease of implementation
- When code running in a virtual thread calls a blocking I/O operation in the java.* API, the runtime performs a non-blocking OS call and automatically suspends the virtual thread until it can be resumed later
- The JDK's virtual thread scheduler is a work-stealing ForkJoinPool that operates in FIFO mode
- The parallelism of the scheduler is the number of platform threads available for the purpose of scheduling virtual threads. By default it is equal to the number of available processors, but it can be tuned with the system property jdk.virtualThreadScheduler.parallelism
- ForkJoinPool is distinct from the common pool which is used, for example, in the implementation of parallel streams, and which operates in LIFO mode.
- Virtual threads do not require or expect application code to explicitly hand control back to the scheduler; in other words, virtual threads are not cooperative
- The scheduler does not currently implement time sharing for virtual threads. Time sharing is the forceful preemption of a thread that has consumed an allotted quantity of CPU time. While time sharing can be effective at reducing the latency of some tasks when there are a relatively small number of platform threads and CPU utilization is at 100%, it is not clear that time sharing would be as effective with a million virtual threads
